### PR TITLE
add exchange address to wallet options

### PR DESCRIPTION
**Pull request by antonis-bc**

### CODE REVIEW

**Comment by mpfluger** [comment]
These are specific to certain currencies, we should probably keep those separate. We can either add them to the existing per currency settings or have a per currency object inside the `exchangeAddresses` object.

**Comment by mpfluger** [comment]
Nice, thanks! Is this ready to go out across all envs?

**Comment by antonis-bc** [comment]
> Nice, thanks! Is this ready to go out across all envs?

@i think so @schnogz to confirm

**Comment by mpfluger** [comment]
That's deployed in all environments

**Pull request merged**
